USER_ACL_CACHE = '_acl_cache'
GROUP_ACL_CACHE = '_group_acl_cache'

APPLICATION_INITIALIZATION_MODULE = 'ampcms_app'

CONTENT_TYPE_CONTEXT_DATA_MODEL = 'data_model'
CONTENT_TYPE_CONTEXT_CHILDREN = 'children'
CONTENT_TYPE_CONTEXT_HTML_DATA_TAGS = 'data_tags'
CONTENT_TYPE_CONTEXT_MENU_LABEL = 'menu_label'
CONTENT_TYPE_CONTEXT_SELECTED_ITEM = 'selected_item'

JSON_KEY_NAME = 'name'
JSON_KEY_LOCATION = 'location'
JSON_KEY_HTML = 'html'
JSON_KEY_CSS = 'css'
JSON_KEY_JS = 'js'

HTML_DATA_TAG_KEY_NAME = 'name'
HTML_DATA_TAG_KEY_URL = 'url'
HTML_DATA_TAG_KEY_STARTING_URL = 'starting_url'
HTML_DATA_TAG_KEY_APPLICATION = 'application'

HTML_DATA_TAG_PREFIX = 'data-'